name: Docker

on:
  workflow_call:
    
    

jobs:

  docker:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build 
      uses: docker/setup-buildx-action@v2.5.0  
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        # Artifact name
        name: Programa
      
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
          username: morpheus070
            # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.SENHA_DOCKER }}
            # Specifies whether the given registry is ECR (auto, true or false)
          ecr: auto
          # Log out from the Docker registry at the end of a job
          logout: true
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        # Generate SBOM attestation for the build (shorthand for --attest=type=sbom)
        tags: morpheus070/go_ci:${{github.ref_name}} 
      
