name: Docker

on:
  workflow_call:
    
    

jobs:

  docker:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build 
      uses: docker/setup-buildx-action@v2.5.0 
      
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
          username: morpheus070
            # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.SENHA_DOCKER }}
            # Specifies whether the given registry is ECR (auto, true or false)
          ecr: auto
          # Log out from the Docker registry at the end of a job
          logout: true
      
